### ISSUE TITLE
kernel panic in i915 drm driver

### ISSUE THREAD

**Issue by guoch2** [projectacrn/acrn-kernel#148]
When enabling framebuffer console in kconfig, and boot acrn-hypervisor with SOS on KBL NUC7i5D, system panic during booting period.  

[    2.030775] usbcore: registered new interface driver usb_8dev
[    2.030971] e100: Intel(R) PRO/100 Network Driver, 3.5.24-k2-NAPI
[    2.031145] e100: Copyright(c) 1999-2006 Intel Corporation
[    2.031311] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    2.031509] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    2.031677] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    2.031850] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    2.032038] e1000e 0000:00:1f.6: enabling device (0000 -> 0002)
[    2.032461] e1000e 0000:00:1f.6: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    2.064134] fbcon: inteldrmfb (fb0) is primary device
[    2.064202] BUG: unable to handle kernel NULL pointer dereference at 0000000000000274
[    2.064203] PGD 0 P4D 0 
[    2.064206] Oops: 0000 [#1] PREEMPT SMP
[    2.064208] CPU: 2 PID: 7 Comm: kworker/u8:0 Tainted: G     U            4.19.0-acrn-quilt-2e5dc0ac-dirty #4
[    2.064209] Hardware name: Intel Corporation NUC7i5DNHE/NUC7i5DNB, BIOS DNKBLi5v.86A.0057.2018.1030.1638 10/30/2018
[    2.064214] Workqueue: events_unbound async_run_entry_fn
[    2.064217] RIP: 0010:restore_fbdev_mode_atomic+0x138/0x1d0
[    2.064219] Code: 8e 9e 00 00 00 49 63 c6 48 89 de 48 8d 0c c0 49 8b 44 24 50 4c 8d 3c c8 49 8b 47 08 4c 89 ff 41 8b 4f 40 48 8b 80 a8 00 00 00 <8b> 80 74 02 00 00 48 8
[    2.064220] RSP: 0000:ffff9b759b64bb10 EFLAGS: 00010202
[    2.064221] RAX: 0000000000000000 RBX: ffff9b7599985000 RCX: 0000000000000001
[    2.064222] RDX: 0000000000000000 RSI: ffff9b7599985000 RDI: ffff9b759b7ae390
[    2.064223] RBP: ffff9b7599e70578 R08: ffff9b7599c30838 R09: ffff9b7599985000
[    2.064223] R10: 0000000000000898 R11: 0000000000000000 R12: ffff9b7599c43200
[    2.064224] R13: 0000000000000001 R14: 0000000000000002 R15: ffff9b759b7ae390
[    2.064226] FS:  0000000000000000(0000) GS:ffff9b759c500000(0000) knlGS:0000000000000000
[    2.064227] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.064228] CR2: 0000000000000274 CR3: 000000021f813000 CR4: 00000000003406e0
[    2.064229] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    2.064230] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    2.064230] Call Trace:
[    2.064235]  drm_fb_helper_restore_fbdev_mode_unlocked+0x45/0x90
[    2.064237]  drm_fb_helper_set_par+0x29/0x50
[    2.064240]  intel_fbdev_set_par+0x16/0x50
[    2.064243]  fbcon_init+0x485/0x600
[    2.064246]  visual_init+0xd5/0x130
[    2.064249]  do_bind_con_driver+0x1da/0x2c0
[    2.064251]  do_take_over_console+0x123/0x1a0
[    2.064254]  do_fbcon_takeover+0x58/0xb0
[    2.064255]  notifier_call_chain+0x39/0x90
[    2.064258]  blocking_notifier_call_chain+0x3e/0x60
[    2.064260]  register_framebuffer+0x25a/0x340
[    2.064263]  ? vga_switcheroo_client_fb_set+0x19/0x70
[    2.064266]  __drm_fb_helper_initial_config_and_unlock+0x214/0x420
[    2.064268]  intel_fbdev_initial_config+0x14/0x30
[    2.064270]  async_run_entry_fn+0x39/0x160
[    2.064273]  process_one_work+0x19e/0x3d0
[    2.064276]  worker_thread+0x3d/0x390
[    2.064278]  ? wq_sysfs_prep_attrs+0x50/0x50
[    2.064280]  kthread+0x11e/0x140
[    2.064282]  ? kthread_create_worker_on_cpu+0x70/0x70
[    2.064286]  ret_from_fork+0x3a/0x50
[    2.064288] Modules linked in:
[    2.064290] CR2: 0000000000000274
[    2.064293] ---[ end trace 411989f3e12e3001 ]---
[    2.064295] RIP: 0010:restore_fbdev_mode_atomic+0x138/0x1d0
[    2.064296] Code: 8e 9e 00 00 00 49 63 c6 48 89 de 48 8d 0c c0 49 8b 44 24 50 4c 8d 3c c8 49 8b 47 08 4c 89 ff 41 8b 4f 40 48 8b 80 a8 00 00 00 <8b> 80 74 02 00 00 48 8
[    2.064297] RSP: 0000:ffff9b759b64bb10 EFLAGS: 00010202
[    2.064298] RAX: 0000000000000000 RBX: ffff9b7599985000 RCX: 0000000000000001
[    2.064299] RDX: 0000000000000000 RSI: ffff9b7599985000 RDI: ffff9b759b7ae390
[    2.064299] RBP: ffff9b7599e70578 R08: ffff9b7599c30838 R09: ffff9b7599985000
[    2.064300] R10: 0000000000000898 R11: 0000000000000000 R12: ffff9b7599c43200
[    2.064301] R13: 0000000000000001 R14: 0000000000000002 R15: ffff9b759b7ae390
[    2.064302] FS:  0000000000000000(0000) GS:ffff9b759c500000(0000) knlGS:0000000000000000
[    2.064303] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.064304] CR2: 0000000000000274 CR3: 000000021f813000 CR4: 00000000003406e0
[    2.064305] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    2.064306] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    2.064306] Kernel panic - not syncing: Fatal exception
[    2.065111] Kernel Offset: 0x5000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[    2.065111] Rebooting in 10 seconds..

The commit of acrn-kernel is :
commit ef6fc8a2586eb11f55f388fd0e326e1529c35b8d (HEAD -> vxworks, tag: acrn-2018w47.5-140000p, tag: acrn-2018w47.4-140000p, origin/master, master)
Author: Zhi Jin <zhi.jin@intel.com>
Date:   Tue Nov 20 16:15:49 2018 +0800

    config: enable STM protocol for NPK trace
 
And hypervisor is:
commit 29f95021521c076535169cb92f31b092429565a3 (origin/master, origin/HEAD)
Author: Binbin Wu <binbin.wu@intel.com>
Date:   Thu Nov 15 16:31:36 2018 +0800

    hv: vtd: error handling revisit

**Comment by fuzhongl** [comment]
Fixed.
