### ISSUE TITLE
dump hypervisor information after adding virtio-console in DM script

### ISSUE THREAD

**Issue by yonghou2016** [projectacrn/acrn-kernel#15]
in the launch_android script, using following code: 

 _acrn-dm -A -m $mem_size -c $2 -G "$3" -s 0:0,hostbridge -s 1:0,lpc -l com1,stdio \
   -l com1,stdio 
   -s 5,virtio-console,@pty:pty_port \ 
    -s 2,pci-gvt  \
   -s 9,virtio-net,$tap \
   -s 4,virtio-blk,/data/$5/$5.img \
   -s 7,passthru,0/15/0 \
   -s 8,passthru,0/15/1 \
   -s 10,virtio-hyper_dmabuf \
   -s 14,passthru,0/e/0 \
   -s 15,passthru,0/f/0 \
   -s 24,passthru,0/17/0 \
   -s 22,passthru,0/16/0 \
   -M \
   -k /home/root/$5/boot.img-kernel -r /home/root/$5/boot.img-ramdisk.gz \
   -B "initrd=0x48800000 root=/dev/ram0 rw rootwait noxsave maxcpus=$2 \
   nohpet console=ttyS0 no_timer_check ignore_loglevel \
   log_buf_len=16M consoleblank=0 tsc=reliable reboot_panic=p,w \
   intel_iommu=off relative_sleep_states=1 vga=current \
   androidboot.hardware=gordon_peak_acrn firmware_class.path=/vendor/firmware \
   androidboot.selinux=permissive sys.init_log_level=7 \
   androidboot.serialno=$ser \
   i915.enable_rc6=1 drm.atomic=1 i915.nuclear_pageflip=1 i915.enable_fbc=1 \
   i915.modeset=1 drm.vblankoffdelay=1 i915.fastboot=1 i915.enable_guc_loading=0 \
   i915.hpd_sense_invert=0x7 i915.avail_planes_per_pipe=$4 \
   i915.enable_hangcheck=0 use_nuclear_flip=1 \
   firmware_class.path=/vendor/firmware" $vm_name_

**[pre-condition]:** add one line : "  -s 5,virtio-console,@pty:pty_port \"  like the above script 
**[issue]:** the sos console will dump hypervisor log as below:

[112832768us][cpu=1][sev=1][seq=1947]:Error: Unhandled VM exit condition from guest at 0x00000000000009f5 
[112843520us][cpu=1][sev=1][seq=1948]:Exit Reason: 0x0000000000000002 
[112850688us][cpu=1][sev=2][seq=1949]:Exit qualification: 0x0000000000000000 
[112858368us][cpu=1][sev=1][seq=1950]:Error: Unhandled VM exit condition from guest at 0x00000000000009f5 
[112869120us][cpu=1][sev=1][seq=1951]:Exit Reason: 0x0000000000000002 
[112876288us][cpu=1][sev=2][seq=1952]:Exit qualification: 0x0000000000000000 
[112883968us][cpu=1][sev=1][seq=1953]:Error: Unhandled VM exit condition from guest at 0x00000000000009f5 
[112894720us][cpu=1][sev=1][seq=1954]:Exit Reason: 0x0000000000000002 
[112901888us][cpu=1][sev=2][seq=1955]:Exit qualification: 0x0000000000000000 
[112909568us][cpu=1][sev=1][seq=1956]:Error: Unhandled VM exit condition from guest at 0x00000000000009f5 
[112920320us][cpu=1][sev=1][seq=1957]:Exit Reason: 0x0000000000000002 
[112927488us][cpu=1][sev=2][seq=1958]:Exit qualifica

**Comment by jren1** [comment]
@mcao6 please take a look.

**Comment by jren1** [comment]
@yonghou2016 Please move the bug to https://github.com/projectacrn/acrn-hypervisor/issues , we will track the ACRN bugs in one place.

**Comment by mcao6** [comment]
@yonghou2016, just confirm: if remove " -s 5,virtio-console,@pty:pty_port ", this issue is gone?

**Comment by yonghou2016** [comment]
yes, after remove this line, hypervisor log will not be printed out in sos console.

regards
Yong.


________________________________
发件人: Cao, Minggui <notifications@github.com>
发送时间: 2018年6月29日 9:13
收件人: projectacrn/acrn-kernel
抄送: Hou, Yong; Mention
主题: Re: [projectacrn/acrn-kernel] dump hypervisor information after adding virtio-console in DM script (#15)


@yonghou2016<https://github.com/yonghou2016>, just confirm: if remove " -s 5,virtio-console,@pty<https://github.com/pty>:pty_port ", this issue is gone?

―

**Comment by yonghou2016** [comment]
Because  I see “virtio-console” is configured for clearLinux guest  OS, I think it shall be available for Android Guest os as well, is it ?

regards
Yong

发件人: Cao, Minggui [mailto:notifications@github.com]
发送时间: 2018年6月29日 14:24
收件人: projectacrn/acrn-kernel <acrn-kernel@noreply.github.com>
抄送: Hou, Yong <Yong_Hou@mentor.com>; Mention <mention@noreply.github.com>
主题: Re: [projectacrn/acrn-kernel] dump hypervisor information after adding virtio-console in DM script (#15)


I just checked, we have not add the virtio-console in android launch function, I'm not sure what's your requirement fo

**Comment by mcao6** [comment]
no, that need android kernel to support this device. anyway, it should not cause a crash. I'll check the crash issue later.

**Comment by anthonyzxu** [comment]
I think it has nothing to do with virtio-console.
My guess is acrnlog print out the HV log.

Anthony
