### ISSUE TITLE
NUC7i7BNH/NUC7i7DNK preempt kernel

### ISSUE THREAD

**Issue by paspndevops** [projectacrn/acrn-kernel#259]
Hi 
Could you please guide me how to compile preempt and non-preemption SOS  kernel for below NUC's

NUC7i7BNH
NUC7i7DNK

Also guide me how to get less CPU latency in UOS (Fedora)

Thanks in advance !
PASPNaidu

**Comment by fuzhongl** [comment]
https://projectacrn.github.io/latest/getting-started/getting-started.html
