### ISSUE TITLE
Kernel WARNING on SOS while boot up

### ISSUE THREAD

**Issue by cheeyanglee** [projectacrn/acrn-kernel#292]
observed kernel warning on SOS while boot up
Setup : 
NUC7i7DNHE connected to two monitor through both HDMI 
Clear Linux version: 32680
ACRN-hypervisor : v1.6 (acrn-2020w12.5-140000p)
kernel: 4.19.97-104.iot-lts2018-sos
attached [dmesg.log](https://github.com/projectacrn/acrn-kernel/files/4585090/dmesg.log)

>
>[    1.294588] ------------[ cut here ]------------
[    1.294589] plane 1B assertion failure (expected on, current off)
[    1.294601] WARNING: CPU: 3 PID: 7 at drivers/gpu/drm/i915/intel_display.c:1296 assert_plane+0xbf/0xd0
[    1.294602] Modules linked in:
[    1.294603] CPU: 3 PID: 7 Comm: kworker/u8:0 Tainted: G     U            4.19.97-104.iot-lts2018-sos #1
[    1.294604] Hardware name: Intel(R) Client Systems NUC7i7DNHE/NUC7i7DNB, BIOS DNKBLi7v.86A.0056.2018.1003.1622 10/03/2018
[    1.294606] Workqueue: events_unbound async_run_entry_fn
[    1.294607] RIP: 0010:assert_plane+0xbf/0xd0
[    1.294607] Code: 84 c0 48 8b 73 18 48 c7 c2 a2 ff 96 af 49 89 c8 48 c7 c7 58 cc 97 af 4c 0f 44 c2 45 84 e4 48 0f 45 d1 4c 89 c1 e8 0d af 9f ff <0f> 0b e9 74 ff ff ff e8 c5 ab 9f ff 0f 1f 44 00 00 0f 1f 44 00 00
[    1.294608] RSP: 0000:ffff9071e4a4f8a8 EFLAGS: 00010286
[    1.294609] RAX: 0000000000000000 RBX: ffff9071e27af000 RCX: 0000000000000000
[    1.294609] RDX: 0000000000000000 RSI: ffffffffae10177f RDI: 00000000ffffffff
[    1.294609] RBP: ffff9071e4a4f8c8 R08: 000000004d29dee7 R09: ffffffffb003ac70
[    1.294610] R10: 00000000000002ff R11: 0000000000031048 R12: 0000000000000001
[    1.294610] R13: ffff9071e27b1000 R14: ffff9071dec7b000 R15: ffff9071dec7a800
[    1.294611] FS:  0000000000000000(0000) GS:ffff9071e5b80000(0000) knlGS:0000000000000000
[    1.294611] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    1.294612] CR2: 0000000000000000 CR3: 000000022cc14000 CR4: 00000000003406e0
[    1.294612] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    1.294612] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    1.294613] Call Trace:
[    1.294616]  intel_atomic_commit_tail+0xa10/0xba0
[    1.294617]  intel_atomic_commit+0x2c5/0x2f0
[    1.294619]  drm_atomic_commit+0x4a/0x50
[    1.294620]  restore_fbdev_mode_atomic+0x1dc/0x1f0
[    1.294621]  restore_fbdev_mode+0x4a/0x160
[    1.294622]  drm_fb_helper_restore_fbdev_mode_unlocked+0x54/0xb0
[    1.294623]  drm_fb_helper_set_par+0x30/0x60
[    1.294624]  intel_fbdev_set_par+0x1a/0x50
[    1.294626]  fbcon_init+0x486/0x600
[    1.294628]  visual_init+0xdc/0x140
[    1.294629]  do_bind_con_driver+0x1bf/0x2b0
[    1.294630]  do_take_over_console+0x12f/0x1a0
[    1.294631]  do_fbcon_takeover+0x5c/0xb0
[    1.294632]  fbcon_event_notify+0x7b5/0x8fa
[    1.294633]  ? fb_add_videomode+0x84/0x110
[    1.294635]  notifier_call_chain+0x51/0xc0
[    1.294636]  blocking_notifier_call_chain+0x50/0x70
[    1.294637]  fb_notifier_call_chain+0x1b/0x20
[    1.294637]  register_framebuffer+0x215/0x330
[    1.294639]  __drm_fb_helper_initial_config_and_unlock+0x261/0x420
[    1.294640]  drm_fb_helper_initial_config+0x36/0x40
[    1.294640]  intel_fbdev_initial_config+0x18/0x30
[    1.294641]  async_run_entry_fn+0x3e/0x170
[    1.294643]  process_one_work+0x19d/0x3d0
[    1.294644]  worker_thread+0x50/0x3c0
[    1.294645]  kthread+0x12d/0x150
[    1.294646]  ? process_one_work+0x3d0/0x3d0
[    1.294646]  ? kthread_create_worker_on_cpu+0x70/0x70
[    1.294648]  ret_from_fork+0x3a/0x50
[    1.294649] ---[ end trace 4b61e375e6576135 ]---

**Comment by yakuizhao** [comment]
Thanks for reporting the issue.
Can the system work well except the kernel warning info?

**Comment by cheeyanglee** [comment]
yes the system works.

**Comment by yakuizhao** [comment]
@cheeyanglee , This is the known issue. It is mainly related with that the planes on PipeB are assigned to another UOS.
If it can work, please ignore the error info.
Thanks

**Comment by fuzhongl** [comment]
Closed as GVt-g isn't supported since acrn v2.0
