### ISSUE TITLE
Feature Request: Adding VXLAN driver for ACRN -Kernel to support multiple tenant network like from OpenStack

### ISSUE THREAD

**Issue by tunicashashi** [projectacrn/acrn-kernel#310]
Can we add VXLAN driver in kernel ? Or can you suggest me how can I add myself and test.
 Something like:
 - kernel/net/openvswitch/vport-vxlan.ko
- /kernel/drivers/net/vxlan.ko.xz

**Comment by gvancuts** [comment]
Hi @tunicashashi , you should be able to add it yourself by changing the config of our kernel and recompiling it.

The instructions should look like - from your local `acrn-kernel` repository:
* `make menuconfig`
* Load the `kernel_config_uefi_sos` file
* Enable the `VXLAN` driver
* Save the changes and proceed to building this new kernel and modules

Unless there are side-effects to this, this is a good candidate to be merged upstream, so please send a Pull Request to the https://github.com/projectacrn/acrn-kernel once you have tested this.

Hope this helps!

**Comment by tunicashashi** [comment]
Thanks,
Yes, it was helpful. But why we don't add it by default. Does it have some adverse effect?

**Comment by fuzhongl** [comment]
@tunicashashi Thanks for this patch!
Normally, the kernel config is maintained by self since different people may needs different config.
