### ISSUE TITLE
Failed to find module with default SOS config

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-kernel#324]
Hi ACRN Team,

I noticed when I started SOS.
Some modules are missing at startup.

Failed to find module 'autofs4'
Failed to find module 'scsi_dh_alua'
Failed to find module 'scsi_dh_emc'
Failed to find module 'scsi_dh_rdac'
Failed to find module 'dm-multipath'

It's possible to include this modules?

Kernel Config:
[config-5.4.73-PKT-200203T060100Z.txt](https://github.com/projectacrn/acrn-kernel/files/5775733/config-5.4.73-PKT-200203T060100Z.txt)

**Comment by gvancuts** [comment]
Hi @ionutnechita , what is the rootfs you are using (Tumbleweed)?

Is this related with #323 ? It looks like it may but looking for a confirmation ;-)

**Comment by ionutnechita** [comment]
Hi @gvancuts,

For this ticket i use: OpenSUSE Tumbleweed.
And for this ticket ( #323 ) i use Ubuntu 20.04, but in the future I will only use OpenSUSE Tumbleweed.

Thanks.

**Comment by gvancuts** [comment]
Hi @ionutnechita , sorry for the delay, I lost sight of this one. Have you noticed any loss of functionality because of this?

I must admit my first reaction is not to include them as it sounds like there is some user-space components looking for them, but the fact they're missing is not affecting the behaviour of the system. Or am I missing something?

**Comment by ionutnechita** [comment]
This does not affect the functionality or boot part.
Only errors appear in the user space, when loading these modules.

One of them would be more important, but it remains for you to decide whether to include it. ( autofs/autofs4 ).

**Comment by gvancuts** [comment]
I agree with you about `autofs4`. It is a fairly important one since it's used by `automount`. We have this failure on Ubuntu too:
```
systemd[1]: Failed to find module 'autofs4'
```

(the other modules are not used in Ubuntu).

I've sent PR #329 to resolve this.
