### ISSUE TITLE
Update Kernel Image in GSG for Partitioned Mode

### ISSUE THREAD

**Issue by xsltzx** [projectacrn/acrn-kernel#362]
Hello，I have some doubts about this step in GSG for partitioned mode
![9153084c1f82a45d58376e1ac24acc1](https://user-images.githubusercontent.com/57651262/156098998-4b8ae3e8-59ba-4da9-a2c0-b4393445823a.png)

The kernel release info means the original kernel of the target computer itself(for example 5.4.0-89-generic), or it means the Service VM kernel(for example vmlinuz-5.10.65-acrn-service-vm) as well as initrd.img's version. I want to know which version should I choose for partitioned mode, thanks.

**Comment by fuzhongl** [comment]
@xsltzx Sorry for response so later.
It is the original kernel of the target computer itself for pre_launched VMs.
